### ISSUE TITLE
How to parse variables in double curly braces?

### ISSUE THREAD

**Issue by sramakintel** [Azure/azureml-assets#316]
How do I parse the latest pypi versions and latest image tag?

https://github.com/haritha-bendapudi/azureml-assets/blob/313c860843e03787fa7a6ea31461a9f25f54f928/training/general/src/environments/sklearn-1.1-ubuntu20.04-py38-cpu/context/conda_dependencies.yaml#L16 

and 

https://github.com/Azure/azureml-assets/blob/58fd3bf10193ca2e2c0577181572af4d016b1e28/training/general/src/environments/sklearn-1.1-ubuntu20.04-py38-cpu/context/Dockerfile#L1

**Comment by elesel** [comment]
[This script](https://github.com/Azure/azureml-assets/blob/main/scripts/azureml-assets/azureml/assets/update_assets.py) is responsible for replacing those template tags with actual ones. There are a few flags that might be useful depending on whether you want to replace those tags in place or copy the asset to another directory.

Sorry for the delay!
