### ISSUE TITLE
MLIndex yaml example

### ISSUE THREAD

**Issue by benjaminbluhm** [Azure/azureml-assets#984]
### Describe your suggestion

Is there an example of how to create an MLIndex yaml file using azureml rag utilities? I would like to implement my own custom component for faiss index creation and could not find an example of how to produce the yaml file

**Comment by tot0** [comment]
Hi @benjaminbluhm, though the source code is not on Github and easily viewable, it is accessable when installed in your local Python environment (`pip install -U azureml-rag[faiss]`). The logic used in the `build_faiss` component lives in `azureml.rag.tasks.build_faiss`, you can use the Go To Definition functionality of VSCode to open that files contents and see how the Faiss index is built and the MLIndex file written.

A code snippet to create a Faiss index:

```python
from azureml.rag.embeddings import EmbeddingsContainer

embeddings = EmbeddingsContainer.load('<path to parent folder of output of generate_embeddings step>', '<name of child folder output from generate_embeddings step>')

embeddings.write_as_faiss_mlindex('<output path>')
```
This is a bit cumbersome and usability should be improving over time.

This the key snippet of `write_as_faiss_mlindex()` which generates the contents of the MLIndex file:
```python
mlindex_config = {
     "embeddings": self.get_metadata()
}
mlindex_config["index"] = {
     "kind": "faiss",
     "engine": "langchain.vectorstores.FAISS",
     "method": "FlatL2"
}
with open(output_path / "MLIndex", "w") as f:
     yaml.dump(mlindex_config, f)
```

**Comment by benjaminbluhm** [comment]
@tot0 Thank you for your feedback, much appreciated!
